# Form implementation generated from reading ui file '.\ui\check_robot_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CheckRobot(object):
    def setupUi(self, CheckRobot):
        CheckRobot.setObjectName("CheckRobot")
        CheckRobot.resize(402, 89)
        self.exit_button = QtWidgets.QDialogButtonBox(parent=CheckRobot)
        self.exit_button.setGeometry(QtCore.QRect(120, 50, 167, 29))
        self.exit_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 700 9pt \"Segoe UI\";")
        self.exit_button.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.exit_button.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.exit_button.setObjectName("exit_button")
        self.text_info_robot = QtWidgets.QTextBrowser(parent=CheckRobot)
        self.text_info_robot.setGeometry(QtCore.QRect(0, 10, 401, 31))
        self.text_info_robot.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 700 9pt \"Segoe UI\";")
        self.text_info_robot.setObjectName("text_info_robot")

        self.retranslateUi(CheckRobot)
        self.exit_button.accepted.connect(CheckRobot.accept) # type: ignore
        self.exit_button.rejected.connect(CheckRobot.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CheckRobot)

    def retranslateUi(self, CheckRobot):
        _translate = QtCore.QCoreApplication.translate
        CheckRobot.setWindowTitle(_translate("CheckRobot", "Dialog"))
        self.text_info_robot.setHtml(_translate("CheckRobot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🤖 BẠN CÓ CHẮC CHẮN LÀ ROBOT HAY KHÔNG ? 🤖</p></body></html>"))
