# Form implementation generated from reading ui file '.\ui\finding_user.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Found_Users_Page(object):
    def setupUi(self, Found_Users_Page):
        Found_Users_Page.setObjectName("Found_Users_Page")
        Found_Users_Page.resize(1074, 555)
        self.centralwidget = QtWidgets.QWidget(parent=Found_Users_Page)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(440, 460, 169, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.exit_page = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.exit_page.setContentsMargins(0, 0, 0, 0)
        self.exit_page.setObjectName("exit_page")
        self.apply_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.apply_button.setStyleSheet(
            "color: rgb(0, 0, 127);\n"
            "background-color: rgb(255, 255, 255);\n"
            'font: 700 9pt "Segoe UI";'
        )
        self.apply_button.setObjectName("apply_button")
        self.exit_page.addWidget(self.apply_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.cancel_button.setStyleSheet(
            "color: rgb(170, 0, 0);\n"
            "background-color: rgb(255, 255, 255);\n"
            'font: 700 9pt "Segoe UI";'
        )
        self.cancel_button.setObjectName("cancel_button")
        self.exit_page.addWidget(self.cancel_button)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(180, 60, 701, 381))
        self.groupBox.setStyleSheet(
            'font: 700 9pt "Segoe UI";\n' "color: rgb(85, 0, 0);"
        )
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(240, 50, 201, 221))
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap(
                r"C:\Users\phatl\OneDrive - VNU-HCMUS\Desktop\relative_face_recognition_app\client\frontend\ui\picture\demo_ava.jpg"
            )
        )
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 290, 162, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.find_img_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.find_img_label.setStyleSheet(
            "color: rgb(255, 255, 255);\n" 'font: 700 9pt "Segoe UI";'
        )
        self.find_img_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.find_img_label.setObjectName("find_img_label")
        self.verticalLayout.addWidget(self.find_img_label)
        self.upload_pic = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.upload_pic.setStyleSheet(
            'font: 700 9pt "Segoe UI";\n'
            "color: rgb(170, 0, 0);\n"
            "background-color: rgb(255, 255, 255);"
        )
        self.upload_pic.setObjectName("upload_pic")
        self.verticalLayout.addWidget(self.upload_pic)
        self.back_ground = QtWidgets.QLabel(parent=self.centralwidget)
        self.back_ground.setGeometry(QtCore.QRect(0, 0, 1074, 555))
        self.back_ground.setText("")
        self.back_ground.setPixmap(
            QtGui.QPixmap(
                r"C:\Users\phatl\OneDrive - VNU-HCMUS\Desktop\relative_face_recognition_app\client\frontend\ui\picture\hello.png"
            )
        )
        self.back_ground.setScaledContents(True)
        self.back_ground.setWordWrap(True)
        self.back_ground.setOpenExternalLinks(True)
        self.back_ground.setObjectName("back_ground")
        self.back_ground.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.groupBox.raise_()
        Found_Users_Page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Found_Users_Page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 25))
        self.menubar.setObjectName("menubar")
        Found_Users_Page.setMenuBar(self.menubar)

        self.retranslateUi(Found_Users_Page)
        QtCore.QMetaObject.connectSlotsByName(Found_Users_Page)

    def retranslateUi(self, Found_Users_Page):
        _translate = QtCore.QCoreApplication.translate
        Found_Users_Page.setWindowTitle(_translate("Found_Users_Page", "MainWindow"))
        self.apply_button.setText(_translate("Found_Users_Page", "FIND"))
        self.cancel_button.setText(_translate("Found_Users_Page", "CANCEL"))
        self.groupBox.setTitle(_translate("Found_Users_Page", "THÔNG TIN CẦN TÌM"))
        self.find_img_label.setText(
            _translate(
                "Found_Users_Page",
                '<html><head/><body><p align="center">HÌNH ẢNH TÌM KIẾM</p></body></html>',
            )
        )
        self.upload_pic.setText(_translate("Found_Users_Page", "Tải hình ảnh lên"))
